package:
  name: mshr
  version: "1.7.0dev"

source:
  git_url: https://bitbucket.org/fenics-project/mshr.git
  git_tag: master

requirements:
  build:
    - python
    - cmake
    - dolfin ==1.7.0dev
    - gmp
    - mpfr

  run:
    - python
    - dolfin ==1.7.0dev
    - gmp
    - mpfr

test:
  imports:
    - mshr

about:
  home: http://fenicsproject.org/
  license: The GNU Lesser General Public License, version 3.0
  summary: 'Mesh generation component of FEniCS'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
