package:
  name: fenics
  version: "1.7.0dev"

requirements:
  run:
    - mshr ==1.7.0dev
    - dolfin ==1.7.0dev
    - ffc ==1.7.0dev
    - fiat ==1.7.0dev
    - ufl ==1.7.0dev
    - instant ==1.7.0dev

about:
  home: http://www.fenicsproject.org
  summary: 'FEniCS is a collection of free software for automated, efficient solution of differential equations'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
