package:
  name: dolfin
  version: "1.7.0dev"

source:
  git_url: https://bitbucket.org/fenics-project/dolfin.git
  git_tag: master

build:
  # features:
  #   - nox

requirements:
  build:
    - python
    - mkl
    - cmake
    - sphinx
    - libxml2
    - swig ==3.0.7
    - numpy
    - vtk-nox
    - ffc ==1.7.0dev
    - ply
    - boost
    - eigen3
    - petsc <=3.5.2
    - petsc4py <=3.5.1
    - slepc <=3.5.4

  run:
    - python
    - mkl
    - libxml2
    - swig ==3.0.7
    - numpy
    - vtk-nox
    - ffc ==1.7.0dev
    - ufl ==1.7.0dev
    - ply
    - boost
    - eigen3
    - petsc <=3.5.2
    - petsc4py <=3.5.1
    - slepc <=3.5.4

test:
  imports:
    - dolfin

  requires:
    - mkl

about:
  home: http://www.fenicsproject.org
  license: The GNU Lesser General Public License, version 3.0
  summary: 'C++/Python library for solving differential equations'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
